import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ReactNode } from "react";

// Load fonts locally
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the site
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className="dark">
      <body className={geistSans.variable}> {/* Using geistSans */}
        <div className="relative w-full flex justify-center">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
